apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
spec:
  hosts:
    - "{{ .Chart.Name }}.{{ .Values.domain }}"
  gateways:
    - istio-system/dataplane
  http:
    - route:
        - destination:
            host: {{ .Chart.Name }}
            port:
              number: 8501
